### ISSUE TITLE
How to custom CollectionSubfactory

### ISSUE THREAD

**Issue by vvtri** [jorgebodega/typeorm-factory#109]
Hi, I need to create  a Factory like this, field productDetails that has two children, each is one language. How can I do it, or am I missing something ?

```ts
export class ProductDetailFactory extends Factory<ProductDetail> {
  protected entity: Constructable<ProductDetail>;
  protected dataSource: DataSource;
  protected attrs(): FactorizedAttrs<ProductDetail> {
    return {
      description: faker.commerce.productDescription(),
      name: faker.commerce.productName(),
      shortDescription: faker.commerce.productDescription(),
      lang: Language.VN,
      slug: faker.commerce.productName().replace(/\s/g, '-'),
    };
  }
}

export class ProductFactory extends Factory<Product> {
  protected entity: Constructable<Product>;
  protected dataSource: DataSource;
  protected attrs(): FactorizedAttrs<Product> {
    return {
      type: ProductType.SIMPLE,
      status: ProductStatus.ACTIVE,
      isFeatured: false,
      taxStatus: ProductTaxStatus.TAXABLE,
      onSale: true,
      productDetails: [
        {lang: Language.VN,},
        {lang: Language.EN,},
      ]
    };
  }
}
```

**Comment by jorgebodega** [comment]
Hi! Sorry, didn't see the comment.

If I understand well, your problem is that you're using something like a `CollectionSubfactory` but with specific values on every position? I have to check if that use case is already covered with `SingleSubfactory` in an array, but if not, I can try to add it.

**Comment by jorgebodega** [comment]
Please check the new version https://github.com/jorgebodega/typeorm-factory/releases/tag/v1.5.0-next.1 that allow to pass an array of subfactories as well. That could help with your problem.

**Comment by vvtri** [comment]
> Please check the new version https://github.com/jorgebodega/typeorm-factory/releases/tag/v1.5.0-next.1 that allow to pass an array of subfactories as well. That could help with your problem.

Thanks you so much

**Comment by vvtri** [comment]
```ts
export class ProductFactory extends Factory<Product> {
  protected entity: Constructable<Product> = Product;
  protected dataSource: DataSource = dataSource;
  protected attrs(): FactorizedAttrs<Product> {
    return {
      type: ProductType.SIMPLE,
      status: ProductStatus.ACTIVE,
      isFeatured: false,
      taxStatus: ProductTaxStatus.TAXABLE,
      onSale: true,
      productDetails: new LazyInstanceAttribute((instance) => [
        new SingleSubfactory(ProductDetailFactory, {
          product: instance,
          productId: instance.id,
          lang: Language.VN,
        }),
      ]),
    };
  }

  constructor() {
    super();
  }
}
```

It looks like you make change to create function, but I want something like this, it will make creating entity much easily

**Comment by jorgebodega** [comment]
Almost three months before, no response, so I will close the issue. Reopen if needed 👍🏻
