### ISSUE TITLE
Passing information into subfactories?

### ISSUE THREAD

**Issue by jrr** [jorgebodega/typeorm-factory#23]
I have a project still way back on https://github.com/w3tecch/typeorm-seeding , and I'd like to move factories to typeorm-factory. 

So I'm migrating away from using context (which was [removed](https://github.com/jorgebodega/typeorm-seeding/pull/23) in your other library). Using the class-based `extends` factories (nice API design, btw!), I was thinking of using constructors to replace context, like this:

```ts
type FooFactoryContext = { n: number };

export class FooFactory extends Factory<Foo> {
  constructor(private ctx?: FooFactoryContext) {
    super();
  }
  protected entity = Foo;
  protected dataSource = dataSource;
  protected attrs(): FactorizedAttrs<Foo> {
    return {
      description: `item number ${this.ctx?.n || faker.datatype.number(10)}`,
      user: new SingleSubfactory(UserFactory),
    };
  }
}

new FooFactory().make({ description: "stuff" });
new FooFactory({ n: 5 }).make();
```

Is something like this what you had in mind as a replacement for context?

I hit a wall with a pattern in our old usage that I'm struggling to replace. We're passing information from one factory's context into a subfactory's context, like this:

```ts
define<Foo, FooFactoryContext>(Foo, (_, context) => {
  const foo = new Foo();
  foo.title = faker.random.words(3);
  foo.bar = BarFactory({stuff: context?.stuff}) as any;
```

If I continue down the path of using constructors, I think what I need is, a way to pass in a _constructed_ factory into a subfactory, instead of passing in a _constructible_. Something like this:

```ts
protected attrs: FactorizedAttrs<User> = {
  country: new SingleSubfactory(new CountryFactory({customStuff:"here"})),
}
```

Or maybe, alternatively, instead of using constructors, I could pass in some "synthetic" `attrs` that don't have corresponding properties on the Entity:

```ts
protected attrs: FactorizedAttrs<User> = {
  country: new SingleSubfactory(CountryFactory, {
    name: faker.address.country(),
    extraThing: "this doesn't exist on the entity, but could be used by factories"
  }),
}
```

Maybe this is what is meant by _"Attributes objects are superset from the original entity attributes."_ ? ([ref](https://github.com/jorgebodega/typeorm-factory/blob/54705e20e65c0d4053c607a9aaa98d22d0a25e7e/README.md?plain=1#L164)) Does this happen to already work? (TypeScript errors discouraged me, but I haven't tried it interactively)

Do either of these options seem viable? Is there another way to achieve what I'm after?

Thanks for the libraries!

**Comment by jorgebodega** [comment]
Hi!

It's quite interesting what you say. The way factories work right now is designed to allow multiple factories for one entity, and use different constructors and parameters for each one.

And use an instance of a factory instead of just definition is something interesting too. I have to think about that, but the only workaround here for the case you comment, is to use a function that calls the factory desired.

I cannot work on this right now (holidays 🌴) but feel free to add a pull request if you have something in mind.

**Comment by jorgebodega** [comment]
Hi! I'm gonna release a change for this in the `next` tag on NPM, probably today.

Can you check if that fulfills your use case? I found it interesting and is already covered

**Comment by jrr** [comment]
This looks like it will cover the use case, thanks! Closing.
