### ISSUE TITLE
Why is `factory.map` removed?

### ISSUE THREAD

**Issue by michaelm244** [jorgebodega/typeorm-factory#48]
Hi! Curious in moving to this repo over https://github.com/w3tecch/typeorm-seeding.

Curious why `factory.map` is removed though? I've found it very helpful when seeding many records (and actually wanted to contribute an improvement to it).

**Comment by jorgebodega** [comment]
The new way to use factories is to use a defined class, where you can use a function to assign a value to a field.

Also, you can just use some internal state or whatever to have a counter like that.
